// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBXW6wszhJZgP46WcaomRm0TNEdhPJlkSs',
    appId: '1:189679540394:web:83f91a9fea3845866cd8d3',
    messagingSenderId: '189679540394',
    projectId: 'nimi-33d5a',
    authDomain: 'nimi-33d5a.firebaseapp.com',
    databaseURL: 'https://nimi-33d5a-default-rtdb.firebaseio.com',
    storageBucket: 'nimi-33d5a.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyClcjIf_LGtSK_LlnOWUzENAaFRdiKUpsw',
    appId: '1:189679540394:android:a0ed76e9a89d1b756cd8d3',
    messagingSenderId: '189679540394',
    projectId: 'nimi-33d5a',
    databaseURL: 'https://nimi-33d5a-default-rtdb.firebaseio.com',
    storageBucket: 'nimi-33d5a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDkWio1gGETiUqycH3SDPEo7aW-zKVfOLg',
    appId: '1:189679540394:ios:d611daa9b89c9eb16cd8d3',
    messagingSenderId: '189679540394',
    projectId: 'nimi-33d5a',
    databaseURL: 'https://nimi-33d5a-default-rtdb.firebaseio.com',
    storageBucket: 'nimi-33d5a.firebasestorage.app',
    iosBundleId: 'com.example.smartmeter',
  );
}
